### ISSUE TITLE
Skill: (2) Use CoffeeScript in Rails

### ISSUE THREAD

**Issue by snurby7** [snurby7/tc359_rails_final#1]
929e082925 should hopefully complete this issue. Open to improvements though.

@chrisvfritz

**Comment by chrisvfritz** [comment]
:+1: This looks very nice! You don't have to change this, but since you asked, here are some minor improvements I would make.

``` coffeescript
# runs this code only after the entire page has finished loading
$ -> 
  # binds the following code to click on any .reloadable-cat elements
  # notice that i'm targeting a class instead of an ID, leaving open the possibility
  # of adding this functionality to many images on a single page, if we chose to
  $('.reloadable-cat').on 'click', -> 
    # this is very similar, but with some string interpolation instead of concatenation
    # it's not necessarily better - just a personal style preference for me
    @src = "http://thecatapi.com/api/images/get?#{(new Date).getTime()}"
    # this variable starts with $, because it's convention for a jQuery object
    $img = $(@)
     # adds a reloading class
    $img.addClass 'reloading'
    # waits for the new image src to load
    $img.load -> 
      # removes the reloading class
      $img.removeClass 'reloading' 
```

``` erb
<!-- removed the id and onclick event, added the class -->
<img src="<%= cat.url %>" class="reloadable-cat" height="400">
```

``` scss
img.reloadable-cat {
  // making the cursor a pointer, so users know they can click on the cat
  cursor: pointer;
}

// this fades the image a little when it's reloading, so that users can see that
// something is happening. it's odd, but doing something simple like this can
// make the time for an image to load seem much quicker to users
img.reloading {
  opacity: .4;
  transition: opacity 1.5s;
}
```
